spring:
  banner:
    location: classpath:logo.ascii
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  application:
    name: tech-trend-emporium
service:
  dateFormat: yyyy-MM-dd hh:mm:ss
  controller:
    path: /api
server:
  port: ${PORT}
data:
  secretKey: ${SECRET_KEY}
  pathStore: ${PATH_STORE}


