name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Change to project directory
        run: cd /home/runner/work/TTE-app/TTE-app/tte-app

      - name: Set environment variables for secrets
        run: |
          export DB_URL="${{ secrets.DB_URL }}"
          export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          export DB_USERNAME="${{ secrets.DB_USERNAME }}"
          export DB_PORT="${{ secrets.DB_PORT }}"
          export SECRET_KEY="${{ secrets.SECRET_KEY }}"

      - name: look
        run: ls

      - name: Build with Maven
        run: mvn -f /home/runner/work/TTE-app/TTE-app/tte-app/pom.xml clean package

      - name: Build Docker image
        run: |
          docker build -t tech-trend-emporium-app:${{ github.sha }} .

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker image
        run: |
          docker tag tech-trend-emporium-app:${{ github.sha }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/tteapp:${{ github.sha }}

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/tteapp:${{ github.sha }}
