name: CI_PR

on:
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Set environment variables for secrets
        run: |
          export DB_URL="${{ secrets.DB_URL }}"
          export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          export DB_USERNAME="${{ secrets.DB_USERNAME }}"
          export DB_PORT="${{ secrets.DB_PORT }}"
          export SECRET_KEY="${{ secrets.SECRET_KEY }}"
          export PATH_STORE="${{ secrets.PATH_STORE }}"

      - name: Change to project directory
        run: cd /home/runner/work/TTE-app/TTE-app/tte-app

      - name: Build with Maven
        run: |
          mvn -f /home/runner/work/TTE-app/TTE-app/tte-app/pom.xml clean package

      - name: Run tests with JaCoCo coverage
        run: mvn -f tte-app/pom.xml test jacoco:report

      - name: Upload code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: tte-app/target/site/jacoco

      - name: Build Docker image
        run: docker build -t tech-trend-emporium-app:${{ github.event.pull_request.head.sha }} -f Dockerfile .
        working-directory: /home/runner/work/TTE-app/TTE-app/tte-app

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag Docker image
        run: |
          docker tag tech-trend-emporium-app:${{ github.event.pull_request.head.sha }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/tteapp:${{ github.event.pull_request.head.sha }}
      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/tteapp:${{ github.event.pull_request.head.sha }}
